20 Data clean up (#25)
* Data clean up

Data clean up (class, constructor), add unit tests, extract validity function into separate function.

* Correct indentation in _pkgdown.yaml

Correct indentation in _pkgdown.yaml

* Correctig _pkgdown.yaml

Correctig _pkgdown.yaml

* Typo in test-Data-class, clean example

Correct typo in test-Data-class, clean example in Data-class.R

* Addressing comments from 1st PR review

Addressing comments from 1st PR review: minor typographic issues + calling validate_data directly in one test..

* Updating gitleaks link + unpack it

Updating gitleaks link + unpack it

* gitleaks link update

gitleaks link update

* gitleaks version - regexp update

Update of GITLEAKS_VERSION

* gitleaks - quoting underscores

gitleaks - quoting underscores

* gitleaks file path update

* gitleaks update

gitleaks update

* Closes #20

Closes #20

* gitleaks

gitleaks

* gitleaks

gitleaks

* gitleaks

gitleaks

* all_equal help

all_equal help

* Data-class remove styler for the whole file

Closes #20

* Closes #20

Data-class: remove styler changes from the sections which should not be changed

* Closes 20#

Styler for Data-class for only the sections which should be changed within this issue

* Closes #20

Closes #20 - minor reformatting

* polishing

* rm whitespace

* Polishing

Closes #20

* Help update

Help update

Co-authored-by: Daniel Sabanes Bove <daniel.sabanes_bove@roche.com>

diff --git a/.github/workflows/gitleaks.yaml b/.github/workflows/gitleaks.yaml
--- a/.github/workflows/gitleaks.yaml
+++ b/.github/workflows/gitleaks.yaml
@@ -1,3 +1,4 @@
+---
 name: gitleaks
 
 on:
@@ -6,19 +7,39 @@ on:
       - main
       - pre-release
   pull_request:
+    branches:
+      - main
+      - pre-release
+  workflow_call:
+    inputs:
+      additional_args:
+        description: Additional arguments to pass to gitleaks
+        required: false
+        type: string
+        default: ""
 
 jobs:
   gitleaks:
+    name: gitleaks
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repo
         uses: actions/checkout@v2
 
-      - name: Run gitleaks
+      - name: Download and install gitleaks
         run: |
-          GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/zricethezav/gitleaks/releases/latest |  grep -oP '"tag_name": "\K(.*)(?=")')
-          wget https://github.com/zricethezav/gitleaks/releases/download/$GITLEAKS_VERSION/gitleaks-linux-amd64
-          sudo mv gitleaks-linux-amd64 /usr/bin/gitleaks
-          chmod +x /usr/bin/gitleaks
-          gitleaks -v --path . --no-git
+          sudo wget -q \
+            "https://github.com/zricethezav/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" \
+            -O /tmp/gitleaks.tar.gz || \
+            (echo "Error downloading gitleaks ${GITLEAKS_VERSION} tarball" && exit 1)
+          sudo tar -xvzf /tmp/gitleaks.tar.gz || \
+            (echo "Error unarchiving gitleaks ${GITLEAKS_VERSION} tarball" && exit 1)
+          sudo mv gitleaks /usr/bin/. || \
+            (echo "Error moving gitleaks for /usr/bin" && exit 1)
+        shell: bash
+        env:
+          GITLEAKS_VERSION: 8.0.0
+
+      - name: Run gitleaks
+        run: gitleaks -v --no-git ${{ inputs.additional_args }} --path .
         shell: bash
